version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: username 
      POSTGRESS_PASSWORD: password
      POSTGRES_DB: db_teste
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
  